version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${PORT}:${PORT}
    env_file:
      - ./.env
    depends_on:
      - db
    links:
      - db
    networks:
      - api-network
      # - api-network
  db:
    container_name: api-db
    image: postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/data/postgres
      - POSTGRES_DB=${DB_NAME}
    networks:
      - api-network
#    links:
#      - api
    volumes:
      - ./data/database:/data/postgres
    restart: always

networks:
  api-network:
    driver: bridge
